async function main() {}

main().catch(error => console.error(error));
